# Generated by Django 5.1.2 on 2024-11-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laws',
            name='law_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
