# Generated by Django 5.1.2 on 2024-11-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_laws_law_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laws',
            old_name='text',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='laws',
            name='law_name',
            field=models.IntegerField(),
        ),
    ]
