# Generated by Django 5.1.2 on 2024-11-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_text_laws_desc_alter_laws_law_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laws',
            name='law_name',
            field=models.CharField(max_length=100),
        ),
    ]
