# Generated by Django 5.1.3 on 2024-11-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_name_article_article_article_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
