# Generated by Django 5.1.3 on 2024-11-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_article_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='embedding',
            field=models.TextField(),
        ),
    ]
