# Generated by Django 5.1.3 on 2024-11-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_article_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
